server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurityoauth2sso?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update

